all: papa.exe monos.exe
monos.exe: monos.cpp SemaforoArray.cpp 
	g++ monos.cpp SemaforoArray.cpp -o monos.exe
papa.exe: Papa.cpp Semaforo.cpp Buzon2.cpp 
	g++ Papa.cpp Semaforo.cpp Buzon2.cpp -o papa.exe