all: sumaUno.exe PiPorSeries.exe matrices.exe
sumaUno.exe: sumaUno.c
	gcc sumaUno.c -fopenmp -o sumaUno.exe -DDEBUG
PiPorSeries.exe: PiPorSeries.c 
	gcc PiPorSeries.c -fopenmp -o PiPorSeries.exe -DDEBUG
matrices.exe: matrices.c
	gcc matrices.c -fopenmp -o matrices.exe -DDEBUG 