#
# Makefile Semana-07
#
all: processHTML.out matrices.exe
processHTML.out: processHTML.cc 
	g++ -g processHTML.cc -o processHTML.out
matrices.exe: matrices.cpp
	g++ matrices.cpp -o matrices.exe -lpthread -lrt

